Repository dnnsoftware/Dnn.AdminExperience, pull requests merged in 2019-09, with the labels that each got.

#1159 Fix incorrect sites loaded
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/SiteSettings.Web/src/components/siteLanguageSelector/index.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Sites.Web/src/_exportables/src/Components/ListView/index.jsx
Labels: bug, noteworthy

#1124 DNN-29429: Fix SMTP Server Tab UI Issue 3.0.x
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Servers.Web/src/components/Tabs/SmtpServer.jsx
Labels: bug

#1134 Fix tab sorting before they are serialized
  Extensions/Content/Dnn.PersonaBar.Extensions/Components/Sites/SitesController.cs
Labels: bug

#1136 Scheduler: web server dropdown is failing due to javascript error
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/TaskScheduler.Web/src/components/scheduler/index.jsx
Labels: bug, esw

#1142 Style Admin Logs to include line breaks in stack traces
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/AdminLogs.Web/src/components/AdminLog/style.less
Labels: improvement

#1143 Unable to set membership settings "Use Email Address as Username" ON
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Security.Web/src/components/registrationSettings/index.jsx
Labels: bug, esw

#1146 Fix to display IP Filter settings correctly
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Security.Web/src/components/ipFilters/ipFilterEditor/index.jsx
Labels: esw

#1162 Modules get duplicated when try to localize modules
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Pages.Web/src/components/PageLocalization/PageLocalization.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
Labels: improvement

#1164 Delete style overflow after closing PersonaBar
  Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/main.js
Labels: bug

#1166 () Characters that are not illegal are considered illegal characters
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Pages.Web/src/actions/pageSeoActions.js
  Extensions/Content/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
Labels: bug

#1169 Bumps Dnn dependencies to 9.4.0 release packages
  NuGetPackages/NuGetPackages.csproj
  NuGetPackages/app.config
  NuGetPackages/packages.config
Labels: chore

#1172 Added message after localization update finishes
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Pages.Web/src/components/PageLocalization/PageLocalization.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
Labels: esw, improvement

#1066 Fix sitemap settings display
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Seo.Web/src/components/sitemapSettings/providerRow/index.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Seo.Web/src/components/sitemapSettings/providerRow/style.less
Labels: bug

#1089 Blank_Name_is_accepted_as_Group_name
  Extensions/Content/Dnn.PersonaBar.Extensions/Services/RolesController.cs
Labels: bug

#1117 DNN-29164 - Open page settings can't display data for correct page
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Pages.Web/src/components/App.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Pages.Web/src/utils.js
Labels: bug

#1132 remove the dependency of security analyzer on evoq's default.aspx
  Extensions/Content/Dnn.PersonaBar.Extensions/Components/Security/Checks/CheckDefaultPage.cs
  Extensions/Content/Dnn.PersonaBar.Extensions/Components/Security/Resources/sums.resources
  Extensions/Content/Dnn.PersonaBar.Extensions/Components/Security/Utility.cs
Labels: chore

#1120 DNN-31953 - Create multiple pages validation doesn't work when hierarchy is wrong
  Extensions/Content/Dnn.PersonaBar.Extensions/Components/Pages/BulkPagesController.cs
  Extensions/Content/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
Labels: bug

#1139 Search crawlers fails when running on different instances of web farm
  Extensions/Content/Dnn.PersonaBar.Extensions/Components/TaskScheduler/TaskSchedulerController.cs
  Extensions/Content/Dnn.PersonaBar.Extensions/Services/TaskSchedulerController.cs
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/TaskScheduler.Web/src/components/body/index.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/TaskScheduler.Web/src/components/scheduler/index.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/TaskScheduler.Web/src/components/scheduler/schedulerEditor/index.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/TaskScheduler.Web/src/components/scheduler/schedulerRow/index.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/TaskScheduler.Web/src/components/topPane/index.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/TaskScheduler.Web/src/components/topPane/modePanel/index.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/TaskScheduler.Web/src/globals/application.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/TaskScheduler.Web/src/resources/index.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/TaskScheduler.Web/src/services/applicationService.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/TaskScheduler.Web/src/utils/index.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.TaskScheduler/App_LocalResources/TaskScheduler.resx
Labels: improvement

#1126 DNN-30135 - Issue when loading the Persona Bar: Not Thread Safe
  Library/Dnn.PersonaBar.Library/Repository/PersonaBarRepository.cs
Labels: bug

#1167 Social Groups created through the Persona Bar do not appear in the Social Groups
  Extensions/Content/Dnn.PersonaBar.Extensions/Components/Roles/RolesController.cs
Labels: bug

#1180 Add missing keys for data consent
  Extensions/Content/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
Labels: bug
