Repository dnnsoftware/Dnn.AdminExperience, pull requests merged in 2019-05, with the labels that each got.

#939 DNN-27517: add settings to control force logout after password changed function.
  Extensions/Content/Dnn.PersonaBar.Extensions/Services/Dto/UpdateMemberSettingsRequest.cs
  Extensions/Content/Dnn.PersonaBar.Extensions/Services/SecurityController.cs
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Security.Web/src/components/memberManagement/index.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Security/App_LocalResources/Security.resx
Labels: feature

#953 Adjust PersonaBar.UI to build after Extensions project
  Dnn.AdminExperience.sln
Labels: DevOps

#966 Added modules option to css-loader as per breaking change
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/AdminLogs.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Extensions.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Licensing.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Pages.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Prompt.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Roles.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Security.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Seo.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Servers.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/SiteImportExport.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/SiteSettings.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Sites.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/TaskScheduler.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Themes.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Users.Web/src/_exportables/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Users.Web/webpack.config.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Vocabularies.Web/webpack.config.js
Labels: bug

#964 Bump version to v4.0.0
  Build/Symbols/Symbols.dnn
  EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  Extensions/Content/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Extensions/Settings/Dnn.PersonaBar.SearchSettings/Dnn.PersonaBar.SearchSettings.dnn
  Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
  SolutionInfo.cs
Labels: DevOps
