Repository dnnsoftware/Dnn.AdminExperience, pull requests merged in 2019-08, with the labels that each got.

#1072 Fix deleted users search
  Extensions/Content/Dnn.PersonaBar.Extensions/SqlDataProvider/03.00.00.SqlDataProvider
Labels: bug

#1094 Update "About" information for DNN Platform to be more relevant and current
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Licensing.Web/src/actions/licensing.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Licensing.Web/src/components/platform/index.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Licensing.Web/src/components/platform/style.less
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Licensing.Web/src/components/svg/dnn_docs_logo.svg
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Licensing.Web/src/components/svg/dnn_logo_primary.svg
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Licensing.Web/src/components/svg/dnn_technology_editorial.svg
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Licensing.Web/src/components/svg/github.svg
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Licensing.Web/src/components/svg/info_circle.svg
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Licensing.Web/src/components/svg/star_circle.svg
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Licensing.Web/src/constants/actionTypes/licensing.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Licensing.Web/src/reducers/licensingReducer.js
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Licensing.Web/src/services/applicationService.js
  Extensions/Content/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Licensing/App_LocalResources/Licensing.resx
Labels: improvement

#1098 Fixes an issue when creating a new site with a new admin
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Sites.Web/src/components/CreatePortal/index.jsx
Labels: bug

#1115 Updates Dnn dependencies
  NuGetPackages/NuGetPackages.csproj
  NuGetPackages/packages.config
Labels: DevOps

#1099 DNN-31578 - Deleted page can still be selected as parent page - second repository
  Dnn.React.Common/src/PagePicker/index.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Pages.Web/src/components/PageDetails/PageStandard/PageStandard.jsx
  Library/Dnn.PersonaBar.Library/Controllers/TabsController.cs
  Library/Dnn.PersonaBar.UI/Services/TabsController.cs
Labels: bug

#1101 Build front end projects in parallel using lerna
  Build-Yarn-Workspace.ps1
  Build/BuildScripts/Module.build
  lerna.json
  package.json
  yarn.lock
Labels: improvement

#1118 Adds checksums for 9.4.0 Platform
  Extensions/Content/Dnn.PersonaBar.Extensions/Components/Security/Resources/sums.resources
Labels: DevOps
