Repository dnnsoftware/Dnn.AdminExperience, pull requests merged in 2019-06, with the labels that each got.

#986 Fixed wrong path to checksums in Security Analyser
  Extensions/Content/Dnn.PersonaBar.Extensions/Components/Security/Utility.cs
Labels: bug

#985 Fixes css console error on PB modules
  EditBar/Dnn.EditBar.UI/editBar/scripts/util.js
  Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/util.js
Labels: bug

#989 Fixes wrong path in embedded resource for security analyzer
  Extensions/Content/Dnn.PersonaBar.Extensions/Components/Security/Checks/CheckSqlRisk.cs
Labels: bug

#993 Removed "show copyright credits" from PB UI.
  Extensions/Content/Dnn.PersonaBar.Extensions/Services/Dto/SiteSettings/UpdatePrivacySettings.cs
  Extensions/Content/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/SiteSettings.Web/src/components/privacySettings/index.jsx
  Extensions/Content/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
Labels: improvement

#996 Error message while deleting localized version of home page
  Extensions/Content/Dnn.PersonaBar.Extensions/Services/Dto/DnnPageDto.cs
  Extensions/Content/Dnn.PersonaBar.Extensions/Services/PagesController.cs
  Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Pages.Web/src/components/PageLocalization/PageLanguage.jsx
Labels: bug, esw

#995 Replaces deprecated API usages
  Extensions/Content/Dnn.PersonaBar.Extensions/Services/SecurityController.cs
  Library/Dnn.PersonaBar.Library/DTO/UserSettings.cs
  Tests/Dnn.PersonaBar.Users.Tests/Dnn.PersonaBar.Users.Tests.csproj
Labels: improvement
