Repository dnnsoftware/Dnn.AdminExperience, pull requests merged in 2019-04, with the labels that each got.

#648 Upgrade to .NET Framework 4.7.2
  EditBar/Dnn.EditBar.Library/Dnn.EditBar.Library.csproj
  EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.csproj
  Extensions/Content/Dnn.PersonaBar.Pages.Tests/Dnn.PersonaBar.Pages.Tests.csproj
  Extensions/Content/Dnn.PersonaBar.Pages/Dnn.PersonaBar.Pages.csproj
  Extensions/Content/Dnn.PersonaBar.Recyclebin/Dnn.PersonaBar.Recyclebin.csproj
  Extensions/Manage/Dnn.PersonaBar.AdminLogs/Dnn.PersonaBar.AdminLogs.csproj
  Extensions/Manage/Dnn.PersonaBar.Roles/Dnn.PersonaBar.Roles.csproj
  Extensions/Manage/Dnn.PersonaBar.Sites/Dnn.PersonaBar.Sites.csproj
  Extensions/Manage/Dnn.PersonaBar.Themes/Dnn.PersonaBar.Themes.csproj
  Extensions/Manage/Dnn.PersonaBar.Users.Tests/Dnn.PersonaBar.Users.Tests.csproj
  Extensions/Manage/Dnn.PersonaBar.Users/Dnn.PersonaBar.Users.csproj
  Extensions/Settings/Dnn.PersonaBar.ConfigConsole/Dnn.PersonaBar.ConfigConsole.csproj
  Extensions/Settings/Dnn.PersonaBar.Connectors/Dnn.PersonaBar.Connectors.csproj
  Extensions/Settings/Dnn.PersonaBar.CssEditor/Dnn.PersonaBar.CssEditor.csproj
  Extensions/Settings/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
  Extensions/Settings/Dnn.PersonaBar.Licensing/Dnn.PersonaBar.Licensing.csproj
  Extensions/Settings/Dnn.PersonaBar.Prompt/Dnn.PersonaBar.Prompt.csproj
  Extensions/Settings/Dnn.PersonaBar.SearchSettings/Dnn.PersonaBar.SearchSettings.csproj
  Extensions/Settings/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
  Extensions/Settings/Dnn.PersonaBar.Security/Dnn.PersonaBar.Security.csproj
  Extensions/Settings/Dnn.PersonaBar.Seo/Dnn.PersonaBar.Seo.csproj
  Extensions/Settings/Dnn.PersonaBar.Servers/Dnn.PersonaBar.Servers.csproj
  Extensions/Settings/Dnn.PersonaBar.SiteImportExport/Dnn.PersonaBar.SiteImportExport.csproj
  Extensions/Settings/Dnn.PersonaBar.SiteSettings/Dnn.PersonaBar.SiteSettings.csproj
  Extensions/Settings/Dnn.PersonaBar.SqlConsole/Dnn.PersonaBar.SqlConsole.csproj
  Extensions/Settings/Dnn.PersonaBar.TaskScheduler/Dnn.PersonaBar.TaskScheduler.csproj
  Extensions/Settings/Dnn.PersonaBar.Vocabularies/Dnn.PersonaBar.Vocabularies.csproj
  Library/Dnn.PersonaBar.Library/Dnn.PersonaBar.Library.csproj
  Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.csproj
  NuGetPackages/NuGetPackages.csproj
  NuGetPackages/app.config
Labels: noteworthy

#711 update version to v2.0.1
  Build/Symbols/Symbols.dnn
  EditBar/Build/Symbols/Symbols.dnn
  EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  EditBar/SolutionInfo.cs
  Extensions/Build/Symbols/Symbols.dnn
  Extensions/Content/Dnn.PersonaBar.Pages/Dnn.PersonaBar.Pages.dnn
  Extensions/Content/Dnn.PersonaBar.Recyclebin/Dnn.PersonaBar.Recyclebin.dnn
  Extensions/Manage/Dnn.PersonaBar.AdminLogs/Dnn.PersonaBar.AdminLogs.dnn
  Extensions/Manage/Dnn.PersonaBar.Roles/Dnn.PersonaBar.Roles.dnn
  Extensions/Manage/Dnn.PersonaBar.Sites/Dnn.PersonaBar.Sites.dnn
  Extensions/Manage/Dnn.PersonaBar.Themes/Dnn.PersonaBar.Themes.dnn
  Extensions/Manage/Dnn.PersonaBar.Users/Dnn.PersonaBar.Users.dnn
  Extensions/Settings/Dnn.PersonaBar.ConfigConsole/Dnn.PersonaBar.ConfigConsole.dnn
  Extensions/Settings/Dnn.PersonaBar.Connectors/Dnn.PersonaBar.Connectors.dnn
  Extensions/Settings/Dnn.PersonaBar.CssEditor/Dnn.PersonaBar.CssEditor.dnn
  Extensions/Settings/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Extensions/Settings/Dnn.PersonaBar.Licensing/Dnn.PersonaBar.Licensing.dnn
  Extensions/Settings/Dnn.PersonaBar.Prompt/Dnn.PersonaBar.Prompt.dnn
  Extensions/Settings/Dnn.PersonaBar.SearchSettings/Dnn.PersonaBar.SearchSettings.dnn
  Extensions/Settings/Dnn.PersonaBar.Security/Dnn.PersonaBar.Security.dnn
  Extensions/Settings/Dnn.PersonaBar.Seo/Dnn.PersonaBar.Seo.dnn
  Extensions/Settings/Dnn.PersonaBar.Servers/Dnn.PersonaBar.Servers.dnn
  Extensions/Settings/Dnn.PersonaBar.SiteImportExport/Dnn.PersonaBar.SiteImportExport.dnn
  Extensions/Settings/Dnn.PersonaBar.SiteSettings/Dnn.PersonaBar.SiteSettings.dnn
  Extensions/Settings/Dnn.PersonaBar.SqlConsole/Dnn.PersonaBar.SqlConsole.dnn
  Extensions/Settings/Dnn.PersonaBar.TaskScheduler/Dnn.PersonaBar.TaskScheduler.dnn
  Extensions/Settings/Dnn.PersonaBar.Vocabularies/Dnn.PersonaBar.Vocabularies.dnn
  Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
  SolutionInfo.cs
Labels: DevOps

#712 update version to v3.0.0
  Build/Symbols/Symbols.dnn
  EditBar/Build/Symbols/Symbols.dnn
  EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  EditBar/SolutionInfo.cs
  Extensions/Build/Symbols/Symbols.dnn
  Extensions/Content/Dnn.PersonaBar.Pages/Dnn.PersonaBar.Pages.dnn
  Extensions/Content/Dnn.PersonaBar.Recyclebin/Dnn.PersonaBar.Recyclebin.dnn
  Extensions/Manage/Dnn.PersonaBar.AdminLogs/Dnn.PersonaBar.AdminLogs.dnn
  Extensions/Manage/Dnn.PersonaBar.Roles/Dnn.PersonaBar.Roles.dnn
  Extensions/Manage/Dnn.PersonaBar.Sites/Dnn.PersonaBar.Sites.dnn
  Extensions/Manage/Dnn.PersonaBar.Themes/Dnn.PersonaBar.Themes.dnn
  Extensions/Manage/Dnn.PersonaBar.Users/Dnn.PersonaBar.Users.dnn
  Extensions/Settings/Dnn.PersonaBar.ConfigConsole/Dnn.PersonaBar.ConfigConsole.dnn
  Extensions/Settings/Dnn.PersonaBar.Connectors/Dnn.PersonaBar.Connectors.dnn
  Extensions/Settings/Dnn.PersonaBar.CssEditor/Dnn.PersonaBar.CssEditor.dnn
  Extensions/Settings/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Extensions/Settings/Dnn.PersonaBar.Licensing/Dnn.PersonaBar.Licensing.dnn
  Extensions/Settings/Dnn.PersonaBar.Prompt/Dnn.PersonaBar.Prompt.dnn
  Extensions/Settings/Dnn.PersonaBar.SearchSettings/Dnn.PersonaBar.SearchSettings.dnn
  Extensions/Settings/Dnn.PersonaBar.Security/Dnn.PersonaBar.Security.dnn
  Extensions/Settings/Dnn.PersonaBar.Seo/Dnn.PersonaBar.Seo.dnn
  Extensions/Settings/Dnn.PersonaBar.Servers/Dnn.PersonaBar.Servers.dnn
  Extensions/Settings/Dnn.PersonaBar.SiteImportExport/Dnn.PersonaBar.SiteImportExport.dnn
  Extensions/Settings/Dnn.PersonaBar.SiteSettings/Dnn.PersonaBar.SiteSettings.dnn
  Extensions/Settings/Dnn.PersonaBar.SqlConsole/Dnn.PersonaBar.SqlConsole.dnn
  Extensions/Settings/Dnn.PersonaBar.TaskScheduler/Dnn.PersonaBar.TaskScheduler.dnn
  Extensions/Settings/Dnn.PersonaBar.Vocabularies/Dnn.PersonaBar.Vocabularies.dnn
  Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
  SolutionInfo.cs
Labels: DevOps

#723 Add Page Localization tooltips
  Extensions/Content/Dnn.PersonaBar.Pages/Pages.Web/src/components/PageLocalization/Module.jsx
  Extensions/Content/Dnn.PersonaBar.Pages/Pages.Web/src/components/PageLocalization/PageLanguage.jsx
  Extensions/Content/Dnn.PersonaBar.Pages/admin/personaBar/App_LocalResources/Pages.resx
Labels: improvement

#443 Create a module from manifest - An Unknown error has occurred.
  Extensions/Settings/Dnn.PersonaBar.Extensions/Components/CreateModuleController.cs
  Extensions/Settings/Dnn.PersonaBar.Extensions/Extensions.Web/src/components/NewModuleModal/FromManifest/index.jsx
Labels: bug, esw

#396 Display file's full path
  Extensions/Settings/Dnn.PersonaBar.Security/Components/Utility.cs
Labels: improvement

#788 Changes biography security check for a warning
  Extensions/Settings/Dnn.PersonaBar.Security/Components/Checks/CheckBiography.cs
  Extensions/Settings/Dnn.PersonaBar.Security/admin/personaBar/App_LocalResources/Security.resx
Labels: improvement

#789 Placeholder to avoid PersonaBar slide effect
  Library/Dnn.PersonaBar.UI/admin/personaBar/UserControls/PersonaBarContainer.ascx
  Library/Dnn.PersonaBar.UI/admin/personaBar/css/personaBarContainer.css
Labels: esw, improvement

#793 Fixes SSL for cache sync was read from wrong value
  Extensions/Settings/Dnn.PersonaBar.Servers/Services/ServerSettingsPerformanceController.cs
Labels: bug

#790 Restores collapsible behavior in Admin Logs
  Extensions/Manage/Dnn.PersonaBar.AdminLogs/AdminLogs.Web/src/components/LogSettings/LogSettingRow/index.jsx
Labels: bug

#792 Fixes stripping of + is css editor
  Extensions/Settings/Dnn.PersonaBar.CssEditor/Services/CssEditorController.cs
Labels: bug

#791 Fixes not being able to select import package with description
  Extensions/Settings/Dnn.PersonaBar.SiteImportExport/SiteImportExport.Web/src/components/ImportModal/PackageCardOverlay.jsx
  Extensions/Settings/Dnn.PersonaBar.SiteImportExport/SiteImportExport.Web/src/components/ImportModal/PackagesList.jsx
  Extensions/Settings/Dnn.PersonaBar.SiteImportExport/SiteImportExport.Web/src/components/ImportModal/style.less
Labels: bug

#794 Ignores Biography check if deleted
  Extensions/Settings/Dnn.PersonaBar.Security/Components/Checks/CheckBiography.cs
  Extensions/Settings/Dnn.PersonaBar.Security/admin/personaBar/App_LocalResources/Security.resx
Labels: bug

#437 Persona Bar Pages goes blank when no EDIT permission
  Extensions/Content/Dnn.PersonaBar.Pages/Pages.Web/src/components/SearchPage/LazyLoad/LazyLoad.jsx
  Extensions/Content/Dnn.PersonaBar.Pages/Pages.Web/src/components/dnn-persona-bar-page-treeview/src/PersonaBarPageTreeviewInteractor.jsx
Labels: bug, esw

#796 Positions password strenght label to the right
  Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/src/_exportables/src/components/common/Password/index.jsx
  Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/src/_exportables/src/components/common/Password/style.less
Labels: bug

#797 Uses source-map for webpack config
  .gitignore
  Dnn.AdminExperience.sln
  Extensions/Content/Dnn.PersonaBar.Pages/Pages.Web/webpack.config.js
  Extensions/Manage/Dnn.PersonaBar.AdminLogs/AdminLogs.Web/webpack.config.js
  Extensions/Manage/Dnn.PersonaBar.Roles/Roles.Web/webpack.config.js
  Extensions/Manage/Dnn.PersonaBar.Sites/Sites.Web/webpack.config.js
  Extensions/Manage/Dnn.PersonaBar.Themes/Themes.Web/webpack.config.js
  Extensions/Settings/Dnn.PersonaBar.Extensions/Extensions.Web/webpack.config.js
  Extensions/Settings/Dnn.PersonaBar.Licensing/Licensing.Web/webpack.config.js
  Extensions/Settings/Dnn.PersonaBar.Prompt/Prompt.Web/webpack.config.js
  Extensions/Settings/Dnn.PersonaBar.Security/Security.Web/webpack.config.js
  Extensions/Settings/Dnn.PersonaBar.Seo/Seo.Web/webpack.config.js
  Extensions/Settings/Dnn.PersonaBar.Servers/Servers.Web/webpack.config.js
  Extensions/Settings/Dnn.PersonaBar.SiteImportExport/SiteImportExport.Web/webpack.config.js
  Extensions/Settings/Dnn.PersonaBar.SiteSettings/SiteSettings.Web/webpack.config.js
  Extensions/Settings/Dnn.PersonaBar.TaskScheduler/TaskScheduler.Web/webpack.config.js
  Extensions/Settings/Dnn.PersonaBar.Vocabularies/Vocabularies.Web/webpack.config.js
Labels: improvement

#739 - Unable to add module from Disabled page
  EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Js/ExistingModuleDialog.js
Labels: esw, improvement

#795 Fixed an issue with site map priority override
  Extensions/Settings/Dnn.PersonaBar.Seo/Services/SeoController.cs
Labels: bug

#798 Implement new data consent feature in Users PersonaBar extension
  Extensions/Manage/Dnn.PersonaBar.Users.Tests/SearchUsersBySearchTermTest.cs
  Extensions/Manage/Dnn.PersonaBar.Users/Components/Dto/UserBasicDto.cs
  Extensions/Manage/Dnn.PersonaBar.Users/Components/Dto/UserDetailDto.cs
  Extensions/Manage/Dnn.PersonaBar.Users/Components/Dto/UserFilters.cs
  Extensions/Manage/Dnn.PersonaBar.Users/Components/UsersController.cs
  Extensions/Manage/Dnn.PersonaBar.Users/Components/UsersMenuController.cs
  Extensions/Manage/Dnn.PersonaBar.Users/Providers/DataProviders/SqlDataProvider/03.00.00.SqlDataProvider
  Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/package.json
  Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/src/_exportables/package.json
  Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/src/_exportables/src/components/UserTable/DetailRow/index.jsx
  Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/src/_exportables/src/components/UserTable/DetailRow/style.less
  Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/src/_exportables/src/components/UserTable/UserSettings/index.jsx
  Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/src/_exportables/src/components/UserTable/UserSettings/style.less
  Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/src/_exportables/src/components/UserTable/columnSizes.js
  Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/src/_exportables/src/components/UserTable/index.jsx
  Extensions/Manage/Dnn.PersonaBar.Users/admin/personaBar/App_LocalResources/Users.resx
  NuGetPackages/NuGetPackages.csproj
  NuGetPackages/packages.config
Labels: noteworthy

#867 Update dnn-react-common to 2.1.2
  Extensions/Content/Dnn.PersonaBar.Pages/Pages.Web/package.json
  Extensions/Content/Dnn.PersonaBar.Pages/Pages.Web/yarn.lock
  Extensions/Manage/Dnn.PersonaBar.AdminLogs/AdminLogs.Web/package.json
  Extensions/Manage/Dnn.PersonaBar.AdminLogs/AdminLogs.Web/yarn.lock
  Extensions/Manage/Dnn.PersonaBar.Roles/Roles.Web/package.json
  Extensions/Manage/Dnn.PersonaBar.Roles/Roles.Web/yarn.lock
  Extensions/Manage/Dnn.PersonaBar.Sites/Sites.Web/package.json
  Extensions/Manage/Dnn.PersonaBar.Sites/Sites.Web/src/_exportables/package.json
  Extensions/Manage/Dnn.PersonaBar.Sites/Sites.Web/src/_exportables/yarn.lock
  Extensions/Manage/Dnn.PersonaBar.Sites/Sites.Web/yarn.lock
  Extensions/Manage/Dnn.PersonaBar.Themes/Themes.Web/package.json
  Extensions/Manage/Dnn.PersonaBar.Themes/Themes.Web/yarn.lock
  Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/package.json
  Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/src/_exportables/package.json
  Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/src/_exportables/yarn.lock
  Extensions/Manage/Dnn.PersonaBar.Users/Users.Web/yarn.lock
  Extensions/Settings/Dnn.PersonaBar.Extensions/Extensions.Web/package.json
  Extensions/Settings/Dnn.PersonaBar.Extensions/Extensions.Web/yarn.lock
  Extensions/Settings/Dnn.PersonaBar.Licensing/Licensing.Web/package.json
  Extensions/Settings/Dnn.PersonaBar.Licensing/Licensing.Web/yarn.lock
  Extensions/Settings/Dnn.PersonaBar.Prompt/Prompt.Web/package.json
  Extensions/Settings/Dnn.PersonaBar.Prompt/Prompt.Web/yarn.lock
  Extensions/Settings/Dnn.PersonaBar.Security/Security.Web/package.json
  Extensions/Settings/Dnn.PersonaBar.Security/Security.Web/yarn.lock
  Extensions/Settings/Dnn.PersonaBar.Seo/Seo.Web/package.json
  Extensions/Settings/Dnn.PersonaBar.Seo/Seo.Web/yarn.lock
  Extensions/Settings/Dnn.PersonaBar.Servers/Servers.Web/package.json
  Extensions/Settings/Dnn.PersonaBar.Servers/Servers.Web/yarn.lock
  Extensions/Settings/Dnn.PersonaBar.SiteImportExport/SiteImportExport.Web/package.json
  Extensions/Settings/Dnn.PersonaBar.SiteImportExport/SiteImportExport.Web/yarn.lock
  Extensions/Settings/Dnn.PersonaBar.SiteSettings/SiteSettings.Web/package.json
  Extensions/Settings/Dnn.PersonaBar.SiteSettings/SiteSettings.Web/yarn.lock
  Extensions/Settings/Dnn.PersonaBar.TaskScheduler/TaskScheduler.Web/package.json
  Extensions/Settings/Dnn.PersonaBar.TaskScheduler/TaskScheduler.Web/yarn.lock
  Extensions/Settings/Dnn.PersonaBar.Vocabularies/Vocabularies.Web/package.json
  Extensions/Settings/Dnn.PersonaBar.Vocabularies/Vocabularies.Web/yarn.lock
Labels: DevOps
